### 1. Tạo mảng:
- Tạo mảng một chiều (1D) chứa 10 số nguyên ngẫu nhiên từ 0 đến 100.
- Tạo mảng hai chiều (2D) chứa 5 hàng và 3 cột, với các giá trị được khởi tạo bằng 0.
- Tạo mảng ba chiều (3D) chứa 2 khối 3x3x3, với các giá trị được khởi tạo bằng 1.
### 2. Truy cập phần tử:
- Truy cập và in ra phần tử đầu tiên, phần tử cuối cùng của mảng 1D.
- Truy cập và in ra phần tử tại vị trí (2, 1) của mảng 2D.
- Truy cập và thay đổi giá trị của phần tử tại vị trí (1, 1, 1) của mảng 3D.
- Chuyển đổi mảng 2D sang mảng 1D và ngược lại.

In [1]:
import numpy as np

In [28]:
# Tạo mảng một chiều (1D) chứa 10 số nguyên ngẫu nhiên từ 0 đến 100.
d1_ = np.random.randint(100,size=10)
# Tạo mảng hai chiều (2D) chứa 5 hàng và 3 cột, với các giá trị được khởi tạo bằng 0.
d2_ = np.random.randint(100,size=(5,3))
# Tạo mảng ba chiều (3D) chứa 2 khối 3x3x3, với các giá trị được khởi tạo bằng 1.
d3_ = np.ones((3,3,3))
# Truy cập và in ra phần tử đầu tiên, phần tử cuối cùng của mảng 1D.
print(d1_[0],d1_[-1])
# Truy cập và in ra phần tử tại vị trí (2, 1) của mảng 2D.
print(d2_[2,1])
# Truy cập và thay đổi giá trị của phần tử tại vị trí (1, 1, 1) của mảng 3D.
d3_[1,1,1]=0
print(d3_)
d2_.flatten()
d1_.reshape(2,5)

85 8
95
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 0. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


array([[85, 59, 15, 73, 70],
       [40, 50, 15, 46,  8]])

In [49]:
arr1 = np.array([[1,2,3],
                [4,5,6]])
arr2 = np.array([[7,8,9],
                [10,11,12]])

np.sum([arr1,arr2],axis=1)

array([[ 5,  7,  9],
       [17, 19, 21]])

In [46]:
import numpy as np  
a=np.array([[1,4],[3,5]])  
b=np.sum(a,axis=0)  
b  

array([4, 9])