In [30]:
import numpy as np

# Problem 1: Tạo hai ma trận 3x3 với các phần tử integer ngẫu nhiên từ 1 - 10.

In [40]:
np.random.seed(42)
arr1 = np.random.randint(10,size=(3,3))
arr2 = np.random.randint(10,size=(3,3))
arr1,arr2

(array([[6, 3, 7],
        [4, 6, 9],
        [2, 6, 7]]),
 array([[4, 3, 7],
        [7, 2, 5],
        [4, 1, 7]]))

# Problem 2: Thực hiện phép cộng phần tử, nhân từng phần tử, tích vô hướng với hai ma trận vừa được tạo.


In [24]:
# Your code here
sum_ = np.sum([arr1,arr2],axis= 1)
mul = np.multiply(arr1,arr2)
dot = np.dot(arr1,arr2)

# Problem 3: VIết hàm nhận vào một mảng Numpy, sau đó trả về tổng tất cả các phần tử của chúng


In [25]:
# Your code here
def sum_arr(a:np.array):
    result= np.sum(a)
    return result

In [26]:
sum_arr(a=arr1)

50

In [45]:
a = np.array([1,2,3,5,8])
b = np.array([0,3,4,2,1])
c = a+b
c = c*a
arr1.size

9

In [59]:
a = np.array([1,1,1,1,1])
b = np.array([1,0])
a+10

array([11, 11, 11, 11, 11])